

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Deploy Docker image
      with:
        image: repo/luizafurtadoportela/aula_maven_f
        tags: 1.0
        registry: docker.io	
        dockerfile: dockerfile
        username: luizafurtadoportela
        password: ${{ secrets.DOCKER_PASSWORD }}
